name: CI-CD Deploy To Local Docker

on:
  push:
    branches: [ main ]

jobs:

# ---------------------------
# CI JOB (cloud runner)
# ---------------------------
  build-test-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - run: pytest

    - name: Build image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/catsdogs-mlops:latest .

    - name: Login DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/catsdogs-mlops:latest


# ---------------------------
# CD JOB (runs on YOUR LAPTOP)
# ---------------------------
  deploy-local:
    needs: build-test-push
    runs-on: self-hosted

    steps:

    - name: Pull latest image
      run: docker pull ${{ secrets.DOCKER_USERNAME }}/catsdogs-mlops:latest

    - name: Stop old container
      run: docker stop catsdogs-api || true

    - name: Remove old container
      run: docker rm catsdogs-api || true

    - name: Run new container
      run: |
        docker run -d \
          --name catsdogs-api \
          -p 8000:8000 \
          ${{ secrets.DOCKER_USERNAME }}/catsdogs-mlops:latest

    - name: Wait for startup
      run: sleep 15

    - name: Smoke test
      run: curl -f http://localhost:8000/health